local palette = require("rozejin.palette")

local M = {}

local function hl(group, spec)
	vim.api.nvim_set_hl(0, group, spec)
end

function M.groups()
	local c = palette

	return {
		Normal = { fg = c.fg, bg = c.bg },
		NormalNC = { fg = c.fg_soft, bg = c.bg },
		NormalFloat = { fg = c.fg, bg = c.bg_float },
		FloatBorder = { fg = c.rose_soft, bg = c.bg_float },
		FloatTitle = { fg = c.rose, bg = c.bg_float, bold = true },
		ColorColumn = { bg = c.bg_soft },
		Conceal = { fg = c.fg_faint },
		Cursor = { fg = c.bg, bg = c.rose },
		CursorIM = { fg = c.bg, bg = c.rose },
		CursorColumn = { bg = c.bg_cursorline },
		CursorLine = { bg = c.bg_cursorline },
		CursorLineNr = { fg = c.rose, bg = c.bg_cursorline, bold = true },
		DarkenedPanel = { bg = c.bg_statusline },
		Directory = { fg = c.blue, bold = true },
		EndOfBuffer = { fg = c.bg_soft },
		ErrorMsg = { fg = c.red, bold = true },
		FoldColumn = { fg = c.fg_faint, bg = c.bg },
		Folded = { fg = c.fg_faint, bg = c.bg_soft },
		IncSearch = { fg = c.bg, bg = c.rose, bold = true },
		CurSearch = { fg = c.bg, bg = c.rose_soft, bold = true },
		LineNr = { fg = c.fg_nc },
		MatchParen = { fg = c.yellow, bg = c.bg_soft, bold = true },
		ModeMsg = { fg = c.green, bold = true },
		MoreMsg = { fg = c.aqua, bold = true },
		NonText = { fg = c.fg_nc },
		Pmenu = { fg = c.fg, bg = c.bg_popup },
		PmenuSel = { fg = c.bg, bg = c.rose_soft, bold = true },
		PmenuSbar = { bg = c.bg_soft },
		PmenuThumb = { bg = c.rose_soft },
		Question = { fg = c.yellow, bold = true },
		QuickFixLine = { bg = c.bg_soft, bold = true },
		Search = { fg = c.fg, bg = c.bg_search },
		SignColumn = { fg = c.fg_faint, bg = c.bg },
		SpecialKey = { fg = c.fg_nc },
		SpellBad = { sp = c.red, undercurl = true },
		SpellCap = { sp = c.blue, undercurl = true },
		SpellLocal = { sp = c.aqua, undercurl = true },
		SpellRare = { sp = c.purple, undercurl = true },
		StatusLine = { fg = c.fg, bg = c.bg_statusline },
		StatusLineNC = { fg = c.fg_faint, bg = c.bg_statusline },
		TabLine = { fg = c.fg_soft, bg = c.bg_statusline },
		TabLineFill = { bg = c.bg_statusline },
		TabLineSel = { fg = c.bg, bg = c.rose, bold = true },
		Title = { fg = c.rose, bold = true },
		VertSplit = { fg = c.bg_soft, bg = c.bg },
		Visual = { bg = c.bg_visual },
		VisualNOS = { bg = c.bg_visual },
		WarningMsg = { fg = c.orange, bold = true },
		Whitespace = { fg = c.fg_nc },
		WildMenu = { fg = c.bg, bg = c.rose, bold = true },
		WinBar = { fg = c.fg_soft, bg = c.bg },
		WinBarNC = { fg = c.fg_faint, bg = c.bg },
		WinSeparator = { fg = c.bg_soft, bg = c.bg },

		Comment = { fg = c.fg_faint, italic = true },
		Constant = { fg = c.orange },
		String = { fg = c.green },
		Character = { fg = c.green },
		Number = { fg = c.orange },
		Boolean = { fg = c.orange },
		Float = { fg = c.orange },
		Identifier = { fg = c.fg },
		Function = { fg = c.yellow },
		Statement = { fg = c.rose },
		Conditional = { fg = c.rose },
		Repeat = { fg = c.rose },
		Label = { fg = c.rose_soft },
		Operator = { fg = c.fg_soft },
		Keyword = { fg = c.rose },
		Exception = { fg = c.red },
		PreProc = { fg = c.aqua },
		Include = { fg = c.rose_soft },
		Define = { fg = c.rose_soft },
		Macro = { fg = c.aqua },
		PreCondit = { fg = c.aqua },
		Type = { fg = c.blue },
		StorageClass = { fg = c.blue },
		Structure = { fg = c.blue },
		Typedef = { fg = c.blue },
		Special = { fg = c.rose_soft },
		SpecialChar = { fg = c.orange },
		Tag = { fg = c.rose_soft },
		Delimiter = { fg = c.fg_soft },
		SpecialComment = { fg = c.fg_faint, italic = true },
		Debug = { fg = c.red },
		Underlined = { underline = true },
		Bold = { bold = true },
		Italic = { italic = true },
		Ignore = { fg = c.fg_nc },
		Error = { fg = c.red, bg = c.bg_error },
		Todo = { fg = c.bg, bg = c.yellow, bold = true },

		DiagnosticError = { fg = c.red },
		DiagnosticWarn = { fg = c.yellow },
		DiagnosticInfo = { fg = c.blue },
		DiagnosticHint = { fg = c.aqua },
		DiagnosticOk = { fg = c.green },
		DiagnosticUnderlineError = { sp = c.red, undercurl = true },
		DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
		DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
		DiagnosticUnderlineHint = { sp = c.aqua, undercurl = true },
		DiagnosticVirtualTextError = { fg = c.red, bg = c.bg_error },
		DiagnosticVirtualTextWarn = { fg = c.yellow, bg = c.bg_warn },
		DiagnosticVirtualTextInfo = { fg = c.blue, bg = c.bg_info },
		DiagnosticVirtualTextHint = { fg = c.aqua, bg = c.bg_hint },
		DiagnosticFloatingError = { fg = c.red },
		DiagnosticFloatingWarn = { fg = c.yellow },
		DiagnosticFloatingInfo = { fg = c.blue },
		DiagnosticFloatingHint = { fg = c.aqua },
		DiagnosticSignError = { fg = c.red },
		DiagnosticSignWarn = { fg = c.yellow },
		DiagnosticSignInfo = { fg = c.blue },
		DiagnosticSignHint = { fg = c.aqua },
		LspReferenceText = { bg = c.bg_reference },
		LspReferenceRead = { bg = c.bg_reference },
		LspReferenceWrite = { bg = c.bg_reference, underline = true },

		DiffAdd = { bg = c.bg_diff_add },
		DiffChange = { bg = c.bg_diff_change },
		DiffDelete = { bg = c.bg_diff_delete },
		DiffText = { bg = c.bg_visual },
		Added = { fg = c.green },
		Changed = { fg = c.blue },
		Removed = { fg = c.red },

		GitSignsAdd = { fg = c.green },
		GitSignsChange = { fg = c.blue },
		GitSignsDelete = { fg = c.red },

		TelescopeNormal = { fg = c.fg, bg = c.bg_float },
		TelescopeBorder = { fg = c.bg_reference, bg = c.bg_float },
		TelescopePromptNormal = { fg = c.fg, bg = c.bg_popup },
		TelescopePromptBorder = { fg = c.bg_reference, bg = c.bg_popup },
		TelescopePromptPrefix = { fg = c.rose, bg = c.bg_popup, bold = true },
		TelescopePromptCounter = { fg = c.fg_faint, bg = c.bg_popup },
		TelescopePromptTitle = { fg = c.rose, bg = c.bg_reference, bold = true },
		TelescopeResultsNormal = { fg = c.fg_soft, bg = c.bg_float },
		TelescopeResultsBorder = { fg = c.bg_reference, bg = c.bg_float },
		TelescopeResultsTitle = { fg = c.rose_soft, bg = c.bg_reference, bold = true },
		TelescopePreviewNormal = { fg = c.fg, bg = c.bg_float },
		TelescopePreviewBorder = { fg = c.bg_reference, bg = c.bg_float },
		TelescopePreviewTitle = { fg = c.blue, bg = c.bg_reference, bold = true },
		TelescopeSelection = { fg = c.fg, bg = c.bg_cursorline },
		TelescopeSelectionCaret = { fg = c.rose, bg = c.bg_reference, bold = true },
		TelescopeMatching = { fg = c.rose, bold = true },
		TelescopeMultiSelection = { fg = c.purple, bg = c.bg_float, bold = true },
		TelescopePreviewLine = { bg = c.bg_cursorline },
		TelescopePreviewMatch = { fg = c.rose, bg = c.bg_search, bold = true },

		PmenuKind = { fg = c.rose_soft, bg = c.bg_popup },
		PmenuKindSel = { fg = c.bg, bg = c.rose_soft, bold = true },
		PmenuExtra = { fg = c.fg_faint, bg = c.bg_popup },
		PmenuExtraSel = { fg = c.bg, bg = c.rose_soft },
		PmenuMatch = { fg = c.rose, bg = c.bg_popup, bold = true },
		PmenuMatchSel = { fg = c.bg, bg = c.rose_soft, bold = true },

		CmpPmenu = { fg = c.fg, bg = c.bg_popup },
		CmpSel = { fg = c.fg, bg = c.bg_cursorline },
		CmpBorder = { fg = c.bg_reference, bg = c.bg_popup },
		CmpDoc = { fg = c.fg, bg = c.bg_float },
		CmpDocBorder = { fg = c.bg_reference, bg = c.bg_float },

		CmpItemAbbr = { fg = c.fg, bg = c.bg_popup },
		CmpItemAbbrDeprecated = { fg = c.fg_nc, bg = c.bg_popup, strikethrough = true },
		CmpItemAbbrMatch = { fg = c.rose, bg = c.bg_popup, bold = true },
		CmpItemAbbrMatchFuzzy = { fg = c.rose_soft, bg = c.bg_popup, bold = true },
		CmpItemMenu = { fg = c.fg_faint, bg = c.bg_popup, italic = true },

		CmpItemKind = { fg = c.rose_soft, bg = c.bg_popup },
		CmpItemKindText = { fg = c.fg_soft, bg = c.bg_popup },
		CmpItemKindMethod = { fg = c.yellow, bg = c.bg_popup },
		CmpItemKindFunction = { fg = c.yellow, bg = c.bg_popup },
		CmpItemKindConstructor = { fg = c.blue, bg = c.bg_popup },
		CmpItemKindField = { fg = c.fg_soft, bg = c.bg_popup },
		CmpItemKindVariable = { fg = c.fg, bg = c.bg_popup },
		CmpItemKindClass = { fg = c.blue, bg = c.bg_popup },
		CmpItemKindInterface = { fg = c.blue, bg = c.bg_popup },
		CmpItemKindModule = { fg = c.aqua, bg = c.bg_popup },
		CmpItemKindProperty = { fg = c.fg_soft, bg = c.bg_popup },
		CmpItemKindUnit = { fg = c.orange, bg = c.bg_popup },
		CmpItemKindValue = { fg = c.orange, bg = c.bg_popup },
		CmpItemKindEnum = { fg = c.blue, bg = c.bg_popup },
		CmpItemKindKeyword = { fg = c.rose, bg = c.bg_popup },
		CmpItemKindSnippet = { fg = c.green, bg = c.bg_popup },
		CmpItemKindColor = { fg = c.rose_soft, bg = c.bg_popup },
		CmpItemKindFile = { fg = c.blue, bg = c.bg_popup },
		CmpItemKindReference = { fg = c.aqua, bg = c.bg_popup },
		CmpItemKindFolder = { fg = c.blue, bg = c.bg_popup },
		CmpItemKindEnumMember = { fg = c.orange, bg = c.bg_popup },
		CmpItemKindConstant = { fg = c.orange, bg = c.bg_popup },
		CmpItemKindStruct = { fg = c.blue, bg = c.bg_popup },
		CmpItemKindEvent = { fg = c.rose_soft, bg = c.bg_popup },
		CmpItemKindOperator = { fg = c.fg_soft, bg = c.bg_popup },
		CmpItemKindTypeParameter = { fg = c.blue, bg = c.bg_popup },

		CmpGhostText = { fg = c.fg_nc, italic = true },

		BlinkCmpMenu = { fg = c.fg, bg = c.bg_popup },
		BlinkCmpMenuBorder = { fg = c.bg_reference, bg = c.bg_popup },
		BlinkCmpMenuSelection = { fg = c.bg, bg = c.rose_soft, bold = true },
		BlinkCmpScrollBarThumb = { bg = c.rose_soft },
		BlinkCmpScrollBarGutter = { bg = c.bg_soft },

		-- Keep item groups foreground-only so Blink's selection highlight can
		-- paint the full row instead of being overridden column by column.
		BlinkCmpLabel = { fg = c.fg },
		BlinkCmpLabelDeprecated = { fg = c.fg_nc, strikethrough = true },
		BlinkCmpLabelMatch = { fg = c.rose, bold = true },
		BlinkCmpLabelDetail = { fg = c.fg_faint },
		BlinkCmpLabelDescription = { fg = c.fg_faint, italic = true },
		BlinkCmpKind = { fg = c.rose_soft },
		BlinkCmpKindText = { fg = c.fg_soft },
		BlinkCmpKindMethod = { fg = c.yellow },
		BlinkCmpKindFunction = { fg = c.yellow },
		BlinkCmpKindConstructor = { fg = c.blue },
		BlinkCmpKindField = { fg = c.fg_soft },
		BlinkCmpKindVariable = { fg = c.fg },
		BlinkCmpKindClass = { fg = c.blue },
		BlinkCmpKindInterface = { fg = c.blue },
		BlinkCmpKindModule = { fg = c.aqua },
		BlinkCmpKindProperty = { fg = c.fg_soft },
		BlinkCmpKindUnit = { fg = c.orange },
		BlinkCmpKindValue = { fg = c.orange },
		BlinkCmpKindEnum = { fg = c.blue },
		BlinkCmpKindKeyword = { fg = c.rose },
		BlinkCmpKindSnippet = { fg = c.green },
		BlinkCmpKindColor = { fg = c.rose_soft },
		BlinkCmpKindFile = { fg = c.blue },
		BlinkCmpKindReference = { fg = c.aqua },
		BlinkCmpKindFolder = { fg = c.blue },
		BlinkCmpKindEnumMember = { fg = c.orange },
		BlinkCmpKindConstant = { fg = c.orange },
		BlinkCmpKindStruct = { fg = c.blue },
		BlinkCmpKindEvent = { fg = c.rose_soft },
		BlinkCmpKindOperator = { fg = c.fg_soft },
		BlinkCmpKindTypeParameter = { fg = c.blue },
		BlinkCmpSource = { fg = c.fg_faint, italic = true },
		BlinkCmpGhostText = { fg = c.fg_nc, italic = true },

		BlinkCmpDoc = { fg = c.fg, bg = c.bg_float },
		BlinkCmpDocBorder = { fg = c.bg_reference, bg = c.bg_float },
		BlinkCmpDocSeparator = { fg = c.bg_reference, bg = c.bg_float },
		BlinkCmpDocCursorLine = { bg = c.bg_cursorline },
		BlinkCmpSignatureHelp = { fg = c.fg, bg = c.bg_float },
		BlinkCmpSignatureHelpBorder = { fg = c.bg_reference, bg = c.bg_float },
		BlinkCmpSignatureHelpActiveParameter = { fg = c.yellow, bold = true, underline = true },

		["@annotation"] = { fg = c.aqua },

		["@attribute"] = { fg = c.aqua },
		["@boolean"] = { fg = c.orange },
		["@character"] = { fg = c.green },
		["@character.special"] = { fg = c.orange },
		["@comment"] = { fg = c.fg_faint, italic = true },
		["@comment.documentation"] = { fg = c.fg_faint, italic = true },
		["@conceal"] = { fg = c.fg_nc },
		["@constant"] = { fg = c.orange },
		["@constant.builtin"] = { fg = c.orange },
		["@constant.macro"] = { fg = c.aqua },
		["@constructor"] = { fg = c.blue },
		["@diff.plus"] = { fg = c.green },
		["@diff.minus"] = { fg = c.red },
		["@diff.delta"] = { fg = c.blue },
		["@function"] = { fg = c.yellow },
		["@function.builtin"] = { fg = c.yellow },
		["@function.call"] = { fg = c.yellow },
		["@function.method"] = { fg = c.yellow },
		["@function.macro"] = { fg = c.aqua },
		["@keyword"] = { fg = c.rose },
		["@keyword.conditional"] = { fg = c.rose },
		["@keyword.coroutine"] = { fg = c.rose },
		["@keyword.debug"] = { fg = c.red },
		["@keyword.directive"] = { fg = c.aqua },
		["@keyword.directive.define"] = { fg = c.aqua },
		["@keyword.exception"] = { fg = c.red },
		["@keyword.function"] = { fg = c.rose },
		["@keyword.import"] = { fg = c.rose_soft },
		["@keyword.modifier"] = { fg = c.rose_soft },
		["@keyword.operator"] = { fg = c.rose },
		["@keyword.repeat"] = { fg = c.rose },
		["@keyword.return"] = { fg = c.rose },
		["@keyword.storage"] = { fg = c.blue },
		["@label"] = { fg = c.rose_soft },
		["@markup"] = { fg = c.fg },
		["@markup.emphasis"] = { italic = true },
		["@markup.heading"] = { fg = c.rose, bold = true },
		["@markup.link"] = { fg = c.blue, underline = true },
		["@markup.link.label"] = { fg = c.aqua },
		["@markup.link.url"] = { fg = c.green, underline = true },
		["@markup.list"] = { fg = c.rose_soft },
		["@markup.math"] = { fg = c.orange },
		["@markup.quote"] = { fg = c.fg_soft, italic = true },
		["@markup.raw"] = { fg = c.green },
		["@markup.raw.block"] = { fg = c.green },
		["@module"] = { fg = c.blue },
		["@module.builtin"] = { fg = c.blue },
		["@namespace"] = { fg = c.blue },
		["@none"] = {},
		["@number"] = { fg = c.orange },
		["@number.float"] = { fg = c.orange },
		["@operator"] = { fg = c.fg_soft },
		["@property"] = { fg = c.fg },
		["@punctuation.bracket"] = { fg = c.fg_soft },
		["@punctuation.delimiter"] = { fg = c.fg_soft },
		["@punctuation.special"] = { fg = c.rose_soft },
		["@spell"] = {},
		["@string"] = { fg = c.green },
		["@string.documentation"] = { fg = c.green },
		["@string.escape"] = { fg = c.orange },
		["@string.regexp"] = { fg = c.yellow },
		["@string.special"] = { fg = c.orange },
		["@string.special.path"] = { fg = c.green },
		["@string.special.symbol"] = { fg = c.orange },
		["@string.special.url"] = { fg = c.blue, underline = true },
		["@tag"] = { fg = c.rose_soft },
		["@tag.attribute"] = { fg = c.aqua },
		["@tag.delimiter"] = { fg = c.fg_soft },
		["@type"] = { fg = c.blue },
		["@type.builtin"] = { fg = c.blue },
		["@type.definition"] = { fg = c.blue },
		["@type.qualifier"] = { fg = c.rose_soft },
		["@variable"] = { fg = c.fg },
		["@variable.builtin"] = { fg = c.orange },
		["@variable.member"] = { fg = c.fg_soft },
		["@variable.parameter"] = { fg = c.fg_soft, italic = true },

		["@lsp.type.class"] = { link = "@type" },
		["@lsp.type.comment"] = { link = "@comment" },
		["@lsp.type.decorator"] = { link = "@attribute" },
		["@lsp.type.enum"] = { link = "@type" },
		["@lsp.type.enumMember"] = { link = "@constant" },
		["@lsp.type.function"] = { link = "@function" },
		["@lsp.type.interface"] = { link = "@type" },
		["@lsp.type.macro"] = { link = "@function.macro" },
		["@lsp.type.method"] = { link = "@function.method" },
		["@lsp.type.namespace"] = { link = "@module" },
		["@lsp.type.parameter"] = { link = "@variable.parameter" },
		["@lsp.type.property"] = { link = "@property" },
		["@lsp.type.struct"] = { link = "@type" },
		["@lsp.type.type"] = { link = "@type" },
		["@lsp.type.typeParameter"] = { link = "@type.definition" },
		["@lsp.type.variable"] = { link = "@variable" },
	}
end

function M.apply()
	vim.cmd("highlight clear")
	if vim.fn.exists("syntax_on") == 1 then
		vim.cmd("syntax reset")
	end

	vim.o.termguicolors = true
	vim.g.colors_name = "rozejin"

	for group, spec in pairs(M.groups()) do
		hl(group, spec)
	end
end

return M
