# rozejin for kitty

background #1d2021
foreground #eadfe2
selection_background #43313a
selection_foreground #eadfe2
cursor #ff9fc0
cursor_text_color #1d2021
url_color #aac3cf
active_border_color #ff9fc0
inactive_border_color #353039
active_tab_background #ff9fc0
active_tab_foreground #1d2021
inactive_tab_background #181b1c
inactive_tab_foreground #c8b7bb
tab_bar_background #181b1c

color0  #1d2021
color8  #433b3e

color1  #de6f8f
color9  #ff9fc0

color2  #bfd2c0
color10 #d6e5d6

color3  #d8c299
color11 #e5d1a6

color4  #b7c5de
color12 #c9d5ea

color5  #c9b3d9
color13 #e7b9c9

color6  #aac3cf
color14 #c1d6df

color7  #c8b7bb
color15 #eadfe2
